return {
    Title = "子嗣掌控",
    Description = "控制太吾与他人发生关系时的生育参数。",
    Version = "2.0.0.0",
    Author = "RedContritio",
    Source = 0,
    Cover = "",
    GameVersion = "1.0.7",
    BackendPlugins = {
        "FertilityControl.Backend.dll",
    },
    DefaultSettings = {
        { SettingType = "Toggle", Key = "SetAllFertility", DisplayName = "指定总生育能力", DefaultValue = false },
        { SettingType = "Slider", Key = "AllFertilityValue", DisplayName = "总生育能力值", MinValue = 0, MaxValue = 15000, StepSize = 100, DefaultValue = 7500 },
        { SettingType = "Toggle", Key = "SetFatherFertility", DisplayName = "指定父方生育能力", DefaultValue = false },
        { SettingType = "Slider", Key = "FatherFertilityValue", DisplayName = "父方生育能力值", MinValue = 0, MaxValue = 15000, StepSize = 10, DefaultValue = 100 },
        { SettingType = "Toggle", Key = "SetMotherFertility", DisplayName = "指定母方生育能力", DefaultValue = false },
        { SettingType = "Slider", Key = "MotherFertilityValue", DisplayName = "母方生育能力值", MinValue = 0, MaxValue = 15000, StepSize = 10, DefaultValue = 100 },
        { SettingType = "Toggle", Key = "SetPregnancyRate", DisplayName = "指定怀孕概率", DefaultValue = false },
        { SettingType = "Slider", Key = "PregnancyRate", DisplayName = "怀孕概率 (%)", MinValue = 0, MaxValue = 100, StepSize = 1, DefaultValue = 50 },
        { SettingType = "Toggle", Key = "SetCricketRate", DisplayName = "指定蛐蛐概率", DefaultValue = false },
        { SettingType = "Slider", Key = "CricketRate", DisplayName = "蛐蛐概率 (%)", MinValue = 0, MaxValue = 100, StepSize = 1, DefaultValue = 10 },
        { SettingType = "Toggle", Key = "DisableInbreeding", DisplayName = "禁止近亲畸形", Description = "太吾参与的近亲生育不会产生先天畸形", DefaultValue = false },
        { SettingType = "Toggle", Key = "DebugMode", DisplayName = "调试模式", DefaultValue = false },
    },
    TagList = { "Extensions" },
    HasArchive = true,
    ChangeConfig = false,
    NeedRestartWhenSettingChanged = false,
    Visibility = 0,
}
