return {
    Title = "太吾必孕妙法",
    Description = "太吾与他人发生关系时，控制怀孕的概率和方式。",
    Version = "1.0.0.0",
    Author = "RedContritio",
    Source = 0,
    Cover = "cover.jpg",
    WorkshopCover = "cover.jpg",
    GameVersion = "1.0.44.0",
    BackendPlugins = {
        "FertilityControl.Backend.dll",
    },
    SettingGroups = { "基础设置", "进阶设置" },
    DefaultSettings = {
        { SettingType = "Dropdown", Key = "PregnancyCarrierMode", GroupName = "基础设置",
          DisplayName = "谁来怀孕",
          Description = "选择实际怀孕的一方；默认保持正式版母方怀孕",
          Options = { "原生父方怀孕", "原生母方怀孕", "固定太吾怀孕", "固定对方怀孕" },
          DefaultValue = 1 },
        { SettingType = "Toggle", Key = "SetFatherFertility", GroupName = "进阶设置", DisplayName = "指定父方生育能力", DefaultValue = false },
        { SettingType = "Slider", Key = "FatherFertilityValue", GroupName = "进阶设置", DisplayName = "父方生育能力值", MinValue = 0, MaxValue = 15000, StepSize = 10, DefaultValue = 100 },
        { SettingType = "Toggle", Key = "SetMotherFertility", GroupName = "进阶设置", DisplayName = "指定母方生育能力", DefaultValue = false },
        { SettingType = "Slider", Key = "MotherFertilityValue", GroupName = "进阶设置", DisplayName = "母方生育能力值", MinValue = 0, MaxValue = 15000, StepSize = 10, DefaultValue = 100 },
        { SettingType = "Toggle", Key = "AlwaysPregnant", GroupName = "基础设置", DisplayName = "必定怀孕", Description = "太吾参与时怀孕判定必定成功（100%，且无视生育力为0的限制；子嗣数量上限仍由「忽略子嗣数量上限」控制）", DefaultValue = false },
        { SettingType = "Toggle", Key = "AllowNonstandardPregnancyRoles", GroupName = "基础设置", DisplayName = "允许同性生育", Description = "跳过正式版父方/母方性别判定，允许男男、女女等组合进入怀孕判定", DefaultValue = false },
        { SettingType = "Toggle", Key = "IgnoreChildLimit", GroupName = "基础设置", DisplayName = "忽略子嗣数量上限", Description = "跳过正式版按生育力限制已有亲生子女数量的检查", DefaultValue = false },
        { SettingType = "Toggle", Key = "AlwaysCricket", GroupName = "基础设置", DisplayName = "必定生蛐蛐", Description = "太吾参与的新怀孕必定产出蛐蛐（与原生一致，会消耗促织缘归零）", DefaultValue = false },
        { SettingType = "Toggle", Key = "DisableInbreeding", GroupName = "基础设置", DisplayName = "近亲不会畸形", Description = "太吾参与的近亲生育不会产生先天畸形", DefaultValue = false },
    },
    TagList = { "Extensions" },
    HasArchive = false,
    ChangeConfig = false,
    NeedRestartWhenSettingChanged = false,
    Visibility = 0,
    -- 创意工坊发布元数据（游戏上传后写入；持久化在此，避免重新部署时被覆盖丢失）。
    FileId = 3755111308,
    UpdateLogList = {
        { Timestamp = 1782845621 },
    },
}
