return {
    Title = "观音识蛐蛐",
    Description = "捕捉蛐蛐时，根据蛐蛐的叫声计算出品级，让蛐蛐叫声也有品级颜色。",
    Version = "1.1.2.0",
    Author = "RedContritio",
    Source = 0,
    Cover = "cover.jpg",
    WorkshopCover = "cover.jpg",
    DetailImageList = {
        "details_1.png",
    },
    GameVersion = "1.0.52",
    FrontendPlugins = {
        "CricketSingGradeColor.Frontend.dll",
    },
    SettingGroups = { "声音品级", "高品盲盒" },
    DefaultSettings = {
        { SettingType = "Dropdown", Key = "BlendMode", GroupName = "声音品级",
          DisplayName = "声音品级权重",
          Description = "计算规则，音量优先最准确。",
          Options = { "音高优先", "均衡", "音量优先" },
          DefaultValue = 2 },
        { SettingType = "Toggle", Key = "EnableBlindBox", GroupName = "高品盲盒",
          DisplayName = "启用高品盲盒",
          Description = "声音品级达到下方门槛及以上时，捕蛐蛐小游戏的叫声圈改用盲盒色，保留抓捕悬念（仅捕捉小游戏生效，斗蛐蛐/收藏罐仍显示真实色）。",
          DefaultValue = false },
        { SettingType = "Dropdown", Key = "BlindBoxThreshold", GroupName = "高品盲盒",
          DisplayName = "盲盒门槛品级",
          Description = "声音品级达到该档及以上才触发盲盒；同时作为下方“随机高/低品级”的高低分界。",
          Options = {
              "<color=#80817F>九品</color>",
              "<color=#DCDEE0>八品</color>",
              "<color=#9EB767>七品</color>",
              "<color=#5D92C3>六品</color>",
              "<color=#509296>五品</color>",
              "<color=#885390>四品</color>",
              "<color=#BE8A2F>三品</color>",
              "<color=#CE5D20>二品</color>",
              "<color=#D43F38>一品</color>",
          },
          DefaultValue = 7 },
        { SettingType = "Dropdown", Key = "BlindBoxMode", GroupName = "高品盲盒",
          DisplayName = "盲盒形式",
          Description = "高品蛐蛐的叫声圈如何显示。随机的高/低以门槛品级分界；固定默认白色＝还原原版白色涟漪。",
          Options = { "随机展示为低品级", "随机展示为高品级", "固定一品", "固定九品", "固定门槛品级", "固定默认白色" },
          DefaultValue = 2 },
    },
    TagList = {
        "Extensions",
    },
    HasArchive = false,
    ChangeConfig = false,
    NeedRestartWhenSettingChanged = false,
    Visibility = 0,
    FileId = 3753793159,
    UpdateLogList = {
        { Timestamp = 1783451019 },
        { Timestamp = 1783451062 },
    },
}
