return {
    Title = "梦中情人",
    Description = "让太吾成为万千少女的梦中情人，在梦中就会爱上太吾乃至疯狂表白求婚。\n通过配置，可以筛选让满足特定条件的 NPC 主动对太吾产生爱慕、表白与求婚。",
    Version = "1.0.5.0",
    Author = "RedContritio",
    Source = 0,
    Cover = "cover.jpg",
    WorkshopCover = "cover.jpg",
    GameVersion = "1.0.52",
    BackendPlugins = {
        "DreamLover.Backend.dll",
    },
    SettingGroups = { "功能开关", "性别", "地理", "年龄", "好感", "立场", "魅力", "品级", "入魔", "关系过滤", "求婚规则" },
    DefaultSettings = {
        -- 功能开关
        { SettingType = "Toggle", Key = "EnableEnamor", GroupName = "功能开关", DisplayName = "主动爱慕", Description = "NPC主动对太吾产生倾心爱慕", DefaultValue = true },
        { SettingType = "Toggle", Key = "EnablePursued", GroupName = "功能开关", DisplayName = "主动表白", Description = "爱慕太吾的NPC主动表白，成为两情相悦", DefaultValue = true },
        { SettingType = "Toggle", Key = "EnableMarry", GroupName = "功能开关", DisplayName = "主动求婚", Description = "两情相悦的NPC主动求婚", DefaultValue = true },
        { SettingType = "Toggle", Key = "ForgetMe", GroupName = "功能开关", DisplayName = "心去难留", Description = "襄王有意，神女无心。不被太吾回应的单恋者将断绝爱慕", DefaultValue = false },
        -- 性别（六项为「或」：NPC 命中任一被勾选的类别即通过；全不勾=无人追求。男/女按生理性别；男生女相=生理男·外貌女、女生男相=生理女·外貌男）
        { SettingType = "Toggle", Key = "AcceptSameGender", GroupName = "性别", DisplayName = "接受同性", Description = "允许与太吾生理同性别的NPC追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "AcceptOppositeGender", GroupName = "性别", DisplayName = "接受异性", Description = "允许与太吾生理异性别的NPC追求太吾", DefaultValue = true },
        { SettingType = "Toggle", Key = "AcceptMale", GroupName = "性别", DisplayName = "接受男性", Description = "允许生理男性NPC追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "AcceptFemale", GroupName = "性别", DisplayName = "接受女性", Description = "允许生理女性NPC追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "AcceptMaleLooksFemale", GroupName = "性别", DisplayName = "接受男生女相", Description = "允许生理男性、外貌女相的NPC追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "AcceptFemaleLooksMale", GroupName = "性别", DisplayName = "接受女生男相", Description = "允许生理女性、外貌男相的NPC追求太吾", DefaultValue = false },
        -- 地理（追求范围，单选·递进：同道 ⊂ 同格 ⊂ 不受距离限制）
        { SettingType = "Dropdown", Key = "Range", GroupName = "地理", DisplayName = "追求范围", Description = "递进：同道=仅太吾的同道(队友)；同格=太吾所在格(含同道)；同区域=太吾所在区域(含同格)；不受距离限制=任意NPC", Options = { "同道", "同格", "同区域", "不受距离限制" }, DefaultValue = 1 },
        { SettingType = "Toggle", Key = "AllowStranger", GroupName = "地理", DisplayName = "允许陌生人爱慕", Description = "允许对与太吾素未谋面（无任何关系记录）的NPC也促成爱慕：会先按游戏原生方式与太吾建立“相识”关系，再爱慕。关闭时这类陌生人会被跳过（默认关；开启多用于同区域/不受距离限制的大范围撮合）。", DefaultValue = false },
        -- 年龄
        { SettingType = "Slider", Key = "MinAge", GroupName = "年龄", DisplayName = "年龄下限", MinValue = 16, MaxValue = 100, StepSize = 1, DefaultValue = 16 },
        { SettingType = "Slider", Key = "MaxAge", GroupName = "年龄", DisplayName = "年龄上限", MinValue = 16, MaxValue = 100, StepSize = 1, DefaultValue = 60 },
        -- 好感（NPC 对太吾的好感档位）
        { SettingType = "Toggle", Key = "Favor_0", GroupName = "好感", DisplayName = "好感-<color=#8E8E8E>血仇</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_1", GroupName = "好感", DisplayName = "好感-<color=#C6272E>痛恨</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_2", GroupName = "好感", DisplayName = "好感-<color=#C6272E>憎恨</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_3", GroupName = "好感", DisplayName = "好感-<color=#C6272E>仇视</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_4", GroupName = "好感", DisplayName = "好感-<color=#C6272E>敌视</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_5", GroupName = "好感", DisplayName = "好感-<color=#C6272E>鄙视</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_6", GroupName = "好感", DisplayName = "好感-<color=#C6272E>陌路</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_7", GroupName = "好感", DisplayName = "好感-<color=#B6B1AB>冷淡</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_8", GroupName = "好感", DisplayName = "好感-<color=#239360>融洽</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Favor_9", GroupName = "好感", DisplayName = "好感-<color=#91CCC9>热忱</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Favor_10", GroupName = "好感", DisplayName = "好感-<color=#1ABAC8>喜爱</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Favor_11", GroupName = "好感", DisplayName = "好感-<color=#B975FF>亲密</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Favor_12", GroupName = "好感", DisplayName = "好感-<color=#E9D382>不渝</color>", DefaultValue = true },
        -- 立场
        { SettingType = "Toggle", Key = "Good_0", GroupName = "立场", DisplayName = "立场-<color=#FFE78F>刚正</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Good_1", GroupName = "立场", DisplayName = "立场-<color=#9FE0DC>仁善</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Good_2", GroupName = "立场", DisplayName = "立场-<color=#FFFFFF>中庸</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Good_3", GroupName = "立场", DisplayName = "立场-<color=#B975FF>叛逆</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Good_4", GroupName = "立场", DisplayName = "立场-<color=#C6272E>唯我</color>", DefaultValue = false },
        -- 魅力
        { SettingType = "Toggle", Key = "Charm_0", GroupName = "魅力", DisplayName = "魅力-<color=#8E8E8E>非人</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Charm_1", GroupName = "魅力", DisplayName = "魅力-<color=#8E8E8E>可憎</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Charm_2", GroupName = "魅力", DisplayName = "魅力-<color=#8E8E8E>不扬</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Charm_3", GroupName = "魅力", DisplayName = "魅力-<color=#B6B1AB>寻常</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Charm_4", GroupName = "魅力", DisplayName = "魅力-<color=#239360>出众</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Charm_5", GroupName = "魅力", DisplayName = "魅力-<color=#91CCC9>瑶碧·瑾瑜</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Charm_6", GroupName = "魅力", DisplayName = "魅力-<color=#B975FF>凤仪·龙姿</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Charm_7", GroupName = "魅力", DisplayName = "魅力-<color=#E9D382>出尘·绝世</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Charm_8", GroupName = "魅力", DisplayName = "魅力-<color=#F3802A>天人</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "RankAutoMin", GroupName = "品级", DisplayName = "品级-自适应下限(随相枢)", Description = "开启后忽略下方品级勾选，仅追求品级≥当前相枢等级(可招募同道的品级，随剧情提升)的NPC", DefaultValue = false },
        -- 品级（九品最低 .. 一品最高；下方逐档勾选在「自适应下限」关闭时才生效）
        { SettingType = "Toggle", Key = "Rank_0", GroupName = "品级", DisplayName = "品级-<color=#80817F>九品</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rank_1", GroupName = "品级", DisplayName = "品级-<color=#DCDEE0>八品</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rank_2", GroupName = "品级", DisplayName = "品级-<color=#9EB767>七品</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_3", GroupName = "品级", DisplayName = "品级-<color=#5D92C3>六品</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_4", GroupName = "品级", DisplayName = "品级-<color=#509296>五品</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_5", GroupName = "品级", DisplayName = "品级-<color=#885390>四品</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_6", GroupName = "品级", DisplayName = "品级-<color=#BE8A2F>三品</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_7", GroupName = "品级", DisplayName = "品级-<color=#CE5D20>二品</color>", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_8", GroupName = "品级", DisplayName = "品级-<color=#D43F38>一品</color>", DefaultValue = true },
        -- 入魔
        { SettingType = "Toggle", Key = "Infect_0", GroupName = "入魔", DisplayName = "入魔-未入邪", DefaultValue = true },
        { SettingType = "Toggle", Key = "Infect_1", GroupName = "入魔", DisplayName = "入魔-<color=#FF0000>相枢入邪</color>", DefaultValue = false },
        { SettingType = "Toggle", Key = "Infect_2", GroupName = "入魔", DisplayName = "入魔-<color=#FF0000>相枢化魔</color>", DefaultValue = false },
        -- 关系过滤（勾选=允许与太吾有该关系的NPC追求太吾；按太吾视角命名）
        { SettingType = "Toggle", Key = "Rel_BloodParent", GroupName = "关系过滤", DisplayName = "关系-太吾亲生父母", Description = "允许太吾的亲生父母追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_BloodChild", GroupName = "关系过滤", DisplayName = "关系-太吾亲生子女", Description = "允许太吾的亲生子女追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_BloodSibling", GroupName = "关系过滤", DisplayName = "关系-太吾亲生兄妹", Description = "允许太吾的亲生兄妹追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_AdoptiveParent", GroupName = "关系过滤", DisplayName = "关系-太吾义父义母", Description = "允许太吾的义父义母追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_AdoptiveChild", GroupName = "关系过滤", DisplayName = "关系-太吾义子义女", Description = "允许太吾的义子义女追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_SwornSibling", GroupName = "关系过滤", DisplayName = "关系-义结金兰", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_Mentor", GroupName = "关系过滤", DisplayName = "关系-授业恩师", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_Mentee", GroupName = "关系过滤", DisplayName = "关系-弟子传人", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_Friend", GroupName = "关系过滤", DisplayName = "关系-知心之交", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_Adored", GroupName = "关系过滤", DisplayName = "关系-已有爱慕", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_Enemy", GroupName = "关系过滤", DisplayName = "关系-敌对", DefaultValue = true },
        -- 求婚规则
        { SettingType = "Toggle", Key = "IgnoreGang", GroupName = "求婚规则", DisplayName = "无视门派规章", Description = "允许门派禁婚的NPC求婚", DefaultValue = false },
        { SettingType = "Toggle", Key = "MonkKiller", GroupName = "求婚规则", DisplayName = "出家人", Description = "允许出家身份的NPC求婚", DefaultValue = false },
        { SettingType = "Toggle", Key = "CharmingBonze", GroupName = "求婚规则", DisplayName = "太吾出家也要求婚", DefaultValue = false },
    },
    TagList = { "Extensions" },
    HasArchive = false,
    ChangeConfig = false,
    NeedRestartWhenSettingChanged = false,
    Visibility = 0,
    FileId = 3754290100,
    UpdateLogList = {
        { Timestamp = 1782743190 },
        { Timestamp = 1782838374 },
        { Timestamp = 1783451082 },
    },
}
