return {
    Title = "梦中情人",
    Description = "让太吾成为万千少女的梦中情人，在梦中就会爱上太吾乃至疯狂表白求婚。\n通过配置，可以筛选让满足特定条件的 NPC 主动对太吾产生爱慕、表白与求婚。",
    Version = "1.0.2.0",
    Author = "RedContritio",
    Source = 0,
    Cover = "cover.jpg",
    WorkshopCover = "cover.jpg",
    GameVersion = "1.0.52",
    BackendPlugins = {
        "DreamLover.Backend.dll",
    },
    SettingGroups = { "功能开关", "性别", "地理", "年龄", "档位筛选", "关系过滤", "求婚规则", "调试" },
    DefaultSettings = {
        -- 功能开关
        { SettingType = "Toggle", Key = "EnableEnamor", GroupName = "功能开关", DisplayName = "主动爱慕", Description = "NPC主动对太吾产生倾心爱慕", DefaultValue = true },
        { SettingType = "Toggle", Key = "EnablePursued", GroupName = "功能开关", DisplayName = "主动表白", Description = "爱慕太吾的NPC主动表白，成为两情相悦", DefaultValue = true },
        { SettingType = "Toggle", Key = "EnableMarry", GroupName = "功能开关", DisplayName = "主动求婚", Description = "两情相悦的NPC主动求婚", DefaultValue = true },
        { SettingType = "Toggle", Key = "ForgetMe", GroupName = "功能开关", DisplayName = "心去难留", Description = "襄王有意，神女无心。不被太吾回应的单恋者将断绝爱慕", DefaultValue = false },
        -- 性别（六项为「或」：NPC 命中任一被勾选的类别即通过；全不勾=无人追求。男/女按生理性别；男生女相=生理男·外貌女、女生男相=生理女·外貌男）
        { SettingType = "Toggle", Key = "AcceptSameGender", GroupName = "性别", DisplayName = "接受同性", Description = "允许与太吾生理同性别的NPC追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "AcceptOppositeGender", GroupName = "性别", DisplayName = "接受异性", Description = "允许与太吾生理异性别的NPC追求太吾", DefaultValue = true },
        { SettingType = "Toggle", Key = "AcceptMale", GroupName = "性别", DisplayName = "接受男性", Description = "允许生理男性NPC追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "AcceptFemale", GroupName = "性别", DisplayName = "接受女性", Description = "允许生理女性NPC追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "AcceptMaleLooksFemale", GroupName = "性别", DisplayName = "接受男生女相", Description = "允许生理男性、外貌女相的NPC追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "AcceptFemaleLooksMale", GroupName = "性别", DisplayName = "接受女生男相", Description = "允许生理女性、外貌男相的NPC追求太吾", DefaultValue = false },
        -- 地理（追求范围，单选·递进：同道 ⊂ 同格 ⊂ 不受距离限制）
        { SettingType = "Dropdown", Key = "Range", GroupName = "地理", DisplayName = "追求范围", Description = "递进：同道=仅太吾的同道(队友)；同格=太吾所在格(含同道)；同区域=太吾所在区域(含同格)；不受距离限制=任意NPC", Options = { "同道", "同格", "同区域", "不受距离限制" }, DefaultValue = 1 },
        -- 年龄
        { SettingType = "Slider", Key = "MinAge", GroupName = "年龄", DisplayName = "年龄下限", MinValue = 16, MaxValue = 100, StepSize = 1, DefaultValue = 16 },
        { SettingType = "Slider", Key = "MaxAge", GroupName = "年龄", DisplayName = "年龄上限", MinValue = 16, MaxValue = 100, StepSize = 1, DefaultValue = 60 },
        -- 档位筛选：每档独立勾选，勾哪些就只追求哪些档位的NPC；某维度一个都不勾=该维度无人通过。
        -- 好感（NPC 对太吾的好感档位）
        { SettingType = "Toggle", Key = "Favor_0", GroupName = "档位筛选", DisplayName = "好感-血仇", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_1", GroupName = "档位筛选", DisplayName = "好感-痛恨", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_2", GroupName = "档位筛选", DisplayName = "好感-憎恨", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_3", GroupName = "档位筛选", DisplayName = "好感-仇视", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_4", GroupName = "档位筛选", DisplayName = "好感-敌视", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_5", GroupName = "档位筛选", DisplayName = "好感-鄙视", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_6", GroupName = "档位筛选", DisplayName = "好感-陌路", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_7", GroupName = "档位筛选", DisplayName = "好感-冷淡", DefaultValue = false },
        { SettingType = "Toggle", Key = "Favor_8", GroupName = "档位筛选", DisplayName = "好感-融洽", DefaultValue = true },
        { SettingType = "Toggle", Key = "Favor_9", GroupName = "档位筛选", DisplayName = "好感-热忱", DefaultValue = true },
        { SettingType = "Toggle", Key = "Favor_10", GroupName = "档位筛选", DisplayName = "好感-喜爱", DefaultValue = true },
        { SettingType = "Toggle", Key = "Favor_11", GroupName = "档位筛选", DisplayName = "好感-亲密", DefaultValue = true },
        { SettingType = "Toggle", Key = "Favor_12", GroupName = "档位筛选", DisplayName = "好感-不渝", DefaultValue = true },
        -- 立场
        { SettingType = "Toggle", Key = "Good_0", GroupName = "档位筛选", DisplayName = "立场-刚正", DefaultValue = false },
        { SettingType = "Toggle", Key = "Good_1", GroupName = "档位筛选", DisplayName = "立场-仁善", DefaultValue = true },
        { SettingType = "Toggle", Key = "Good_2", GroupName = "档位筛选", DisplayName = "立场-中庸", DefaultValue = true },
        { SettingType = "Toggle", Key = "Good_3", GroupName = "档位筛选", DisplayName = "立场-叛逆", DefaultValue = false },
        { SettingType = "Toggle", Key = "Good_4", GroupName = "档位筛选", DisplayName = "立场-唯我", DefaultValue = false },
        -- 魅力
        { SettingType = "Toggle", Key = "Charm_0", GroupName = "档位筛选", DisplayName = "魅力-非人", DefaultValue = false },
        { SettingType = "Toggle", Key = "Charm_1", GroupName = "档位筛选", DisplayName = "魅力-可憎", DefaultValue = false },
        { SettingType = "Toggle", Key = "Charm_2", GroupName = "档位筛选", DisplayName = "魅力-不扬", DefaultValue = false },
        { SettingType = "Toggle", Key = "Charm_3", GroupName = "档位筛选", DisplayName = "魅力-寻常", DefaultValue = false },
        { SettingType = "Toggle", Key = "Charm_4", GroupName = "档位筛选", DisplayName = "魅力-出众", DefaultValue = true },
        { SettingType = "Toggle", Key = "Charm_5", GroupName = "档位筛选", DisplayName = "魅力-瑶碧·瑾瑜", DefaultValue = true },
        { SettingType = "Toggle", Key = "Charm_6", GroupName = "档位筛选", DisplayName = "魅力-凤仪·龙姿", DefaultValue = true },
        { SettingType = "Toggle", Key = "Charm_7", GroupName = "档位筛选", DisplayName = "魅力-出尘·绝世", DefaultValue = true },
        { SettingType = "Toggle", Key = "Charm_8", GroupName = "档位筛选", DisplayName = "魅力-天人", DefaultValue = true },
        { SettingType = "Toggle", Key = "RankAutoMin", GroupName = "档位筛选", DisplayName = "品级-自适应下限(随相枢)", Description = "开启后忽略下方品级勾选，仅追求品级≥当前相枢等级(可招募同道的品级，随剧情提升)的NPC", DefaultValue = false },
        -- 品级（九品最低 .. 一品最高；下方逐档勾选在「自适应下限」关闭时才生效）
        { SettingType = "Toggle", Key = "Rank_0", GroupName = "档位筛选", DisplayName = "品级-九品", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rank_1", GroupName = "档位筛选", DisplayName = "品级-八品", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rank_2", GroupName = "档位筛选", DisplayName = "品级-七品", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_3", GroupName = "档位筛选", DisplayName = "品级-六品", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_4", GroupName = "档位筛选", DisplayName = "品级-五品", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_5", GroupName = "档位筛选", DisplayName = "品级-四品", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_6", GroupName = "档位筛选", DisplayName = "品级-三品", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_7", GroupName = "档位筛选", DisplayName = "品级-二品", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rank_8", GroupName = "档位筛选", DisplayName = "品级-一品", DefaultValue = true },
        -- 入魔
        { SettingType = "Toggle", Key = "Infect_0", GroupName = "档位筛选", DisplayName = "入魔-未入邪", DefaultValue = true },
        { SettingType = "Toggle", Key = "Infect_1", GroupName = "档位筛选", DisplayName = "入魔-相枢入邪", DefaultValue = false },
        { SettingType = "Toggle", Key = "Infect_2", GroupName = "档位筛选", DisplayName = "入魔-相枢化魔", DefaultValue = false },
        -- 关系过滤（勾选=允许与太吾有该关系的NPC追求太吾；按太吾视角命名）
        { SettingType = "Toggle", Key = "Rel_BloodParent", GroupName = "关系过滤", DisplayName = "关系-太吾亲生父母", Description = "允许太吾的亲生父母追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_BloodChild", GroupName = "关系过滤", DisplayName = "关系-太吾亲生子女", Description = "允许太吾的亲生子女追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_BloodSibling", GroupName = "关系过滤", DisplayName = "关系-太吾亲生兄妹", Description = "允许太吾的亲生兄妹追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_AdoptiveParent", GroupName = "关系过滤", DisplayName = "关系-太吾义父义母", Description = "允许太吾的义父义母追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_AdoptiveChild", GroupName = "关系过滤", DisplayName = "关系-太吾义子义女", Description = "允许太吾的义子义女追求太吾", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_SwornSibling", GroupName = "关系过滤", DisplayName = "关系-义结金兰", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_Mentor", GroupName = "关系过滤", DisplayName = "关系-授业恩师", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_Mentee", GroupName = "关系过滤", DisplayName = "关系-弟子传人", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_Friend", GroupName = "关系过滤", DisplayName = "关系-知心之交", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_Adored", GroupName = "关系过滤", DisplayName = "关系-已有爱慕", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_Enemy", GroupName = "关系过滤", DisplayName = "关系-敌对", DefaultValue = true },
        -- 求婚规则
        { SettingType = "Toggle", Key = "IgnoreGang", GroupName = "求婚规则", DisplayName = "无视门派规章", Description = "允许门派禁婚的NPC求婚", DefaultValue = false },
        { SettingType = "Toggle", Key = "MarriedKiller", GroupName = "求婚规则", DisplayName = "已婚人士", Description = "保留项：正式版婚姻规则仍会阻止已婚NPC结婚", DefaultValue = false },
        { SettingType = "Toggle", Key = "Polygynous", GroupName = "求婚规则", DisplayName = "太吾多配偶制", Description = "保留项：正式版婚姻规则仍会阻止太吾重婚", DefaultValue = false },
        { SettingType = "Toggle", Key = "MonkKiller", GroupName = "求婚规则", DisplayName = "出家人", Description = "允许出家身份的NPC求婚", DefaultValue = false },
        { SettingType = "Toggle", Key = "CharmingBonze", GroupName = "求婚规则", DisplayName = "太吾出家也要求婚", DefaultValue = false },
        -- 调试
        { SettingType = "Toggle", Key = "DebugMode", GroupName = "调试", DisplayName = "调试模式", DefaultValue = false },
    },
    TagList = { "Extensions" },
    HasArchive = false,
    ChangeConfig = false,
    NeedRestartWhenSettingChanged = false,
    Visibility = 0,
    FileId = 3754290100,
    UpdateLogList = {
        { Timestamp = 1782743190 },
        { Timestamp = 1782838374 },
        { Timestamp = 1783451082 },
    },
}
