return {
    Title = "情难自已",
    Description = "为玩家提供接口，主动触发角色之间的正式版强制行为。",
    Version = "1.0.0.2",
    Author = "RedContritio",
    Source = 0,
    Cover = "",
    GameVersion = "1.0.10",
    BackendPlugins = {
        "ForceEncounter.Backend.dll",
    },
    EventPackages = {
        "ForceEncounter.Events.dll",
    },
    DefaultSettings = {
        { SettingType = "Toggle", Key = "Enabled", DisplayName = "启用接口", DefaultValue = true },
        { SettingType = "Slider", Key = "ActionTimeCostDays", DisplayName = "行动力消耗天数", Description = "内层提交时消耗的行动力天数；设为0时不消耗，也不显示行动力成本", MinValue = 0, MaxValue = 5, StepSize = 1, DefaultValue = 5 },
        { SettingType = "Slider", Key = "ForcedFavorabilityPenalty", DisplayName = "强制好感惩罚", Description = "普通强制路线对目标的好感惩罚；太吾村民和部分亲密豁免按村民惩罚比例计算", MinValue = 0, MaxValue = 30000, StepSize = 100, DefaultValue = 30000 },
        { SettingType = "Slider", Key = "TaiwuVillagerPenaltyPercent", DisplayName = "村民惩罚比例", Description = "太吾村民强制路线、单恋太吾和部分谷中密友亲密豁免使用的好感惩罚比例", MinValue = 0, MaxValue = 100, StepSize = 5, DefaultValue = 30 },
        { SettingType = "Toggle", Key = "ApplyAlertnessOnCombatStart", DisplayName = "开战增加戒心", Description = "进入强制战斗时调用原生敌对开战戒心效果", DefaultValue = true },
        { SettingType = "Toggle", Key = "EnableGuardInterception", DisplayName = "启用护卫阻拦", Description = "目标有护卫时，强制路线先由护卫出面阻拦", DefaultValue = true },
        { SettingType = "Toggle", Key = "EnableTaiwuVillagerGuardInterception", DisplayName = "村民启用护卫", Description = "开启后，太吾村民也会按护卫阻拦规则处理；关闭时村民直接与太吾开战", DefaultValue = false },
        { SettingType = "Toggle", Key = "BecomeEnemyOnForcedRoute", DisplayName = "强制路线结仇", Description = "普通强制成功或失败后，对非太吾村民目标调用原生结仇路径", DefaultValue = true },
        { SettingType = "Toggle", Key = "CreateSecretOnForcedSuccess", DisplayName = "强制成功创建秘闻", Description = "强制路线成功后创建原生强制关系秘闻", DefaultValue = true },
        { SettingType = "Toggle", Key = "CreateSecretOnAcceptedSuccess", DisplayName = "亲密成功创建秘闻", Description = "亲密直通提交成功后创建原生强制关系秘闻", DefaultValue = true },
        { SettingType = "Toggle", Key = "允许未成年", DisplayName = "允许未成年", Description = "关闭后，未成年角色不会显示情难自已交互项", DefaultValue = true },
        { SettingType = "Toggle", Key = "DebugMode", DisplayName = "调试模式", DefaultValue = true },
    },
    TagList = { "Extensions" },
    HasArchive = true,
    ChangeConfig = false,
    NeedRestartWhenSettingChanged = false,
    Visibility = 0,
}
