return {
	Title = "情难自已",
	Description = "让玩家也能像 npc 一样，对心动的目标强行实施侮辱行为",
	Version = "1.0.0.6",
	Author = "RedContritio",
	Source = 0,
	Cover = "cover.png",
	GameVersion = "1.0.20.0",
	BackendPlugins = {
		[1] = "ForceEncounter.Backend.dll",
	},
	EventPackages = {
		[1] = "ForceEncounter.Events.dll",
	},
	DefaultSettings = {
		[1] = {
			SettingType = "Slider",
			Key = "ActionTimeCostDays",
			DisplayName = "行动力消耗天数",
			Description = "强行时消耗的行动力天数；设为 0 不消耗",
			MinValue = 0,
			MaxValue = 5,
			StepSize = 1,
			DefaultValue = 5,
		},
		[2] = {
			SettingType = "Slider",
			Key = "ForcedFavorabilityPenalty",
			DisplayName = "强制好感惩罚",
			Description = "强行发生关系后目标对太吾的好感惩罚",
			MinValue = 0,
			MaxValue = 30000,
			StepSize = 100,
			DefaultValue = 30000,
		},
		[3] = {
			SettingType = "Slider",
			Key = "TaiwuVillagerPenaltyPercent",
			DisplayName = "村民惩罚比例",
			Description = "对太吾村民、单恋太吾者等的好感惩罚折扣",
			MinValue = 0,
			MaxValue = 100,
			StepSize = 5,
			DefaultValue = 30,
		},
		[4] = {
			SettingType = "Toggle",
			Key = "ApplyAlertnessOnCombatStart",
			DisplayName = "开战增加戒心",
			Description = "强行开战时，按袭击增加目标戒心",
			DefaultValue = true,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "EnableGuardInterception",
			DisplayName = "启用护卫阻拦",
			Description = "强行发生关系会被护卫拦截",
			DefaultValue = true,
		},
		[6] = {
			SettingType = "Toggle",
			Key = "EnableTaiwuVillagerGuardInterception",
			DisplayName = "村民启用护卫",
			Description = "开启后太吾村民也受护卫阻拦",
			DefaultValue = false,
		},
		[7] = {
			SettingType = "Toggle",
			Key = "BecomeEnemyOnForcedRoute",
			DisplayName = "强制路线结仇",
			Description = "强行发生关系会导致结仇",
			DefaultValue = true,
		},
		[8] = {
			SettingType = "Toggle",
			Key = "CreateSecretOnForcedSuccess",
			DisplayName = "强制成功创建秘闻",
			Description = "强行发生关系后会产生秘闻",
			DefaultValue = true,
		},
		[9] = {
			SettingType = "Toggle",
			Key = "CreateSecretOnAcceptedSuccess",
			DisplayName = "亲密成功创建秘闻",
			Description = "情投意合后会产生秘闻",
			DefaultValue = true,
		},
		[10] = {
			SettingType = "Toggle",
			Key = "允许未成年",
			DisplayName = "允许未成年",
			Description = "能否对未成年目标「情难自已」",
			DefaultValue = true,
		},
		[11] = {
			SettingType = "Toggle",
			Key = "DebugMode",
			DisplayName = "调试模式",
			GroupName = nil,
			DefaultValue = false,
		},
	},
	TagList = {
		[1] = "Extensions",
	},
	HasArchive = false,
	ChangeConfig = false,
	NeedRestartWhenSettingChanged = false,
	Visibility = 0,
	FileId = 3750485094,
	WorkshopCover = "cover.png",
	UpdateLogList = {
		[1] = {
			Timestamp = 1782240898,
		},
		[2] = {
			Timestamp = 1782241019,
		},
		[3] = {
			Timestamp = 1782241062,
		},
	},
}
