return {
    Title = "情难自已",
    Description = "为玩家提供接口，主动触发角色之间的正式版强制行为。",
    Version = "1.0.0.3",
    Author = "RedContritio",
    Source = 0,
    Cover = "",
    GameVersion = "1.0.10",
    BackendPlugins = {
        "ForceEncounter.Backend.dll",
    },
    EventPackages = {
        "ForceEncounter.Events.dll",
    },
    DefaultSettings = {
        { SettingType = "Slider", Key = "ActionTimeCostDays", DisplayName = "行动力消耗天数", Description = "强行时消耗的行动力天数；设为 0 不消耗", MinValue = 0, MaxValue = 5, StepSize = 1, DefaultValue = 5 },
        { SettingType = "Slider", Key = "ForcedFavorabilityPenalty", DisplayName = "强制好感惩罚", Description = "强行发生关系后目标对太吾的好感惩罚", MinValue = 0, MaxValue = 30000, StepSize = 100, DefaultValue = 30000 },
        { SettingType = "Slider", Key = "TaiwuVillagerPenaltyPercent", DisplayName = "村民惩罚比例", Description = "对太吾村民、单恋太吾者等的好感惩罚折扣", MinValue = 0, MaxValue = 100, StepSize = 5, DefaultValue = 30 },
        { SettingType = "Toggle", Key = "ApplyAlertnessOnCombatStart", DisplayName = "开战增加戒心", Description = "强行开战时，按袭击增加目标戒心", DefaultValue = true },
        { SettingType = "Toggle", Key = "EnableGuardInterception", DisplayName = "启用护卫阻拦", Description = "强行发生关系会被护卫拦截", DefaultValue = true },
        { SettingType = "Toggle", Key = "EnableTaiwuVillagerGuardInterception", DisplayName = "村民启用护卫", Description = "开启后太吾村民也受护卫阻拦", DefaultValue = false },
        { SettingType = "Toggle", Key = "BecomeEnemyOnForcedRoute", DisplayName = "强制路线结仇", Description = "强行发生关系会导致结仇", DefaultValue = true },
        { SettingType = "Toggle", Key = "CreateSecretOnForcedSuccess", DisplayName = "强制成功创建秘闻", Description = "强行发生关系后会产生秘闻", DefaultValue = true },
        { SettingType = "Toggle", Key = "CreateSecretOnAcceptedSuccess", DisplayName = "亲密成功创建秘闻", Description = "情投意合后会产生秘闻", DefaultValue = true },
        { SettingType = "Toggle", Key = "允许未成年", DisplayName = "允许未成年", Description = "关闭后，未成年角色不显示「情难自已」", DefaultValue = true },
        { SettingType = "Toggle", Key = "DebugMode", DisplayName = "调试模式", DefaultValue = true },
    },
    TagList = { "Extensions" },
    HasArchive = true,
    ChangeConfig = false,
    NeedRestartWhenSettingChanged = false,
    Visibility = 0,
}
