<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath>..\Plugins</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\ForceEncounter.Shared\ForceEncounterConstants.cs" Link="ForceEncounterConstants.cs" />
    <Compile Include="..\..\TaiwuMod.Common\TaiwuModSettings.cs" Link="TaiwuModSettings.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="TaiwuModdingLib">
      <HintPath>$(TaiwuBackendDir)\TaiwuModdingLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameData">
      <HintPath>$(TaiwuBackendDir)\GameData.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameData.Common">
      <HintPath>$(TaiwuBackendDir)\GameData.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameData.Shared">
      <HintPath>$(TaiwuBackendDir)\GameData.Shared.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameData.ArchiveData">
      <HintPath>$(TaiwuBackendDir)\GameData.ArchiveData.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameData.Utilities">
      <HintPath>$(TaiwuBackendDir)\GameData.Utilities.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
