return {
    Title = "防绿",
    Description = "防止与太吾有特定关系的NPC的配偶与他人发生关系。",
    Version = "2.0.0.0",
    Author = "RedContritio",
    Source = 0,
    Cover = "",
    GameVersion = "1.0.7",
    BackendPlugins = {
        "AntiNTR.Backend.dll",
    },
    DefaultSettings = {
        { SettingType = "Toggle", Key = "Enabled", DisplayName = "启用防绿", DefaultValue = true },
        { SettingType = "Toggle", Key = "AllowCouple", DisplayName = "能与配偶发生关系", Description = "被保护者的配偶仍可与其合法配偶发生关系", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_Friend", DisplayName = "知心之交", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_BloodBrotherOrSister", DisplayName = "亲生兄妹", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_BloodParent", DisplayName = "亲生父母", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_BloodChild", DisplayName = "亲生子女", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_StepParent", DisplayName = "继父继母", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_StepChild", DisplayName = "继子继女", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_StepBrotherOrSister", DisplayName = "继兄妹", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_AdoptiveParent", DisplayName = "义父义母", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_AdoptiveChild", DisplayName = "义子义女", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_AdoptiveBrotherOrSister", DisplayName = "义亲兄妹", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_Mentor", DisplayName = "授业恩师", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_SwornBrotherOrSister", DisplayName = "义结金兰", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_Mentee", DisplayName = "弟子传人", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_Enemy", DisplayName = "敌对", DefaultValue = false },
        { SettingType = "Toggle", Key = "Rel_Adored", DisplayName = "爱慕", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_HusbandOrWife", DisplayName = "结发夫妻", DefaultValue = true },
        { SettingType = "Toggle", Key = "Rel_PreventAll", DisplayName = "任何人", Description = "保护所有NPC（非太吾双方均无法发生关系）", DefaultValue = false },
        { SettingType = "Toggle", Key = "DebugMode", DisplayName = "调试模式", DefaultValue = false },
    },
    TagList = { "Extensions" },
    HasArchive = true,
    ChangeConfig = false,
    NeedRestartWhenSettingChanged = false,
    Visibility = 0,
}
