<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputPath>..\Plugins</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="TaiwuModdingLib">
      <HintPath>$(TaiwuManagedDir)\TaiwuModdingLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(TaiwuManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameData.Shared">
      <HintPath>$(TaiwuManagedDir)\GameData.Shared.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GameData.Serializer">
      <HintPath>$(TaiwuManagedDir)\GameData.Serializer.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(TaiwuManagedDir)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(TaiwuManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(TaiwuManagedDir)\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(TaiwuManagedDir)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(TaiwuManagedDir)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
